import { createElement } from 'lwc';
import SurveyFiller from 'c/surveyFiller';

describe('c-survey-filler', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-survey-filler', {
            is: SurveyFiller
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});