import { createElement } from 'lwc';
import SurveyCreator from 'c/surveyCreator';

describe('c-survey-creator', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-survey-creator', {
            is: SurveyCreator
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});