import { createElement } from 'lwc';
import ControlStatsChart from 'c/controlStatsChart';

describe('c-control-stats-chart', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-control-stats-chart', {
            is: ControlStatsChart
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});