import { createElement } from 'lwc';
import TopRatedSurveysChart from 'c/topRatedSurveysChart';

describe('c-top-rated-surveys-chart', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-top-rated-surveys-chart', {
            is: TopRatedSurveysChart
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});