import { createElement } from 'lwc';
import SurveyRoleChart from 'c/surveyRoleChart';

describe('c-survey-role-chart', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-survey-role-chart', {
            is: SurveyRoleChart
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});