import { createElement } from 'lwc';
import SurveyResultsChart from 'c/surveyResultsChart';

describe('c-survey-results-chart', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-survey-results-chart', {
            is: SurveyResultsChart
        });

        document.body.appendChild(element);

        expect(1).toBe(1);
    });
});